config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end
  
  root 'home#index'
  
  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'
  
  namespace :admin do
    resources :dashboard, only: [:index]
      
    namespace :users do
      
      resources :users, only: [:index, :destroy] do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end
      end
      resources :filters
    end
  end
  
    namespace :users do
      
      get 'sessions/new'
      
      get 'user/edit' => 'users#edit', as: :edit
      
      get 'user/:username' => 'users#show', as: :show
      
      patch 'user' => 'users#update', as: :update
  
      delete 'user' => 'users#destroy', as: :destroy
      
      resources :users, except: [:show, :edit, :update, :destroy] do
    end

    resources :account_activations, only: [:edit]
    
    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]
    
    resources :preferences, only: [:index]
  end # namespace users

end

app/controllers/admin/users/filters_controller.rb
class Admin::Users::FiltersController < Admin::AdminController
  before_action :load_filters, only: [:index]
  before_action :set_filter, only: [:destroy]
  
  def index
    
  end
  
  def create
    params[:user_filter][:blocked] = (params[:list_kind] == "1")
    params[:user_filter][:trusted] = (params[:list_kind] == "2")
    
    @filter = UserFilter.new(filter_params)
    
    @filter.save
    
  end
  
  
  def destroy
    
    @filter.destroy
    
  end
  
  private
  
  def load_filters
    @all_blocked = UserFilter.all_blocked
    @all_trusted = UserFilter.all_trusted
  end
  
  def set_filter
    @filter = UserFilter.find_by_id(params[:id])
  end
  
  def filter_params
    params.require(:user_filter).permit( :ip_address, 
      :email_provider,
      :blocked, 
      :trusted )
  end
end

app/controllers/admin/users/users_controller.rb
class Admin::Users::UsersController < Admin::AdminController
  before_action :find_user, only: :destroy
  before_action :is_regular_user, only: :destroy

  
  respond_to :html, :js
  
  def index
    params[:list] ||= 'active'

    @users = users_selection(params[:list]).paginate(page: params[:page])

    render locals: { users: UsersDecorator.new(@users), list: params[:list] }
  end
  
  def search
    params[:search] ||= ""
    
    min_characters = 3
    max_characters = 50
      
    unless (min_characters..max_characters).include?(params[:search].length)
      flash.now[:warning] = t('admin.users.users.search.notice.length-must-be-in-interval',
        :min => min_characters,
        :max => max_characters)
      
      @users = User.none.paginate(page: params[:page])
    else
      @users = User.search( params[:search] ).paginate(page: params[:page])
    end

    render :index, locals: { users: UserDecorator.new(@users), list: nil, search: params[:search] }
  end
  
  def destroy
      @user.destroy
      
      flash[:success] = t 'user.notice.success.destroyed'
      
      redirect_to :admin_users_users
  end
  
  private
  
  def find_user
    @user = User.find(params[:id])
  end
  
  def is_regular_user
    redirect_to :admin_users_users unless @user.regular?
  end
  
  def users_selection(kind)
    case kind
      when 'new' then User.newest
      when 'staff' then User.staff
      when 'blocked' then User.all_blocked
      when 'suspected' then User.suspects
      else User.actives
    end
  end
  
end

app/controllers/users/account_activations_controller.rb
class Users::AccountActivationsController < ApplicationController

  def edit
    @user = User.find_by(email: params[:email])
      
    if @user &&
      !@user.activated? &&
      @user.authenticated?(:activation, params[:id])
        @user.activate(request.remote_ip )
        
        log_in @user
        flash[:success] = t('user.notice.success.account-activated')
          
        redirect_to users_dashboard_index_url
    else
      flash[:danger] = t('user.notice.danger.invalid-activation-link')
        
      redirect_to root_url
    end
  end

end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  
  def index
    
  end
end

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)

      if @user
        @user.create_reset_digest
        @user.send_password_reset_email
        @user.log( :request_password_reset, ip_address: request.remote_ip )
        
        flash[:info] = t('password-reset.notice.info.email-sent')

        redirect_to root_url
    else
      flash.now[:danger] = t('password-reset.notice.danger.email-not-found')
      render 'new'
    end
  end
  
  def edit
    render locals: { user: @user }
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      
      @user.log( :password_reset, ip_address: request.remote_ip )
      
      flash[:success] = t('password-reset.notice.success.password-reset')
        
      redirect_to users_dashboard_index_path
    else
      render 'edit'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
  
    def get_user
      @user = User.find_by(email: params[:email])
    end
    
    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
        @user.authenticated?(:reset, params[:id]))
          redirect_to root_url
       end
    end
    
    
    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = t('password-reset.notice.danger.password-expired')
        redirect_to new_users_password_reset_url
      end
    end
    
end

app/controllers/users/preferences_controller.rb
class Users::PreferencesController < ApplicationController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
      
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
          
        if user.regular?
          redirect_back_or users_dashboard_index_path
        else
          redirect_back_or admin_dashboard_index_path
        end
        
      else
        flash[:warning] = t('user.notice.warning.account-not-activated')
        redirect_to root_url
      end
      

    else
      flash.now[:danger] = t('user.notice.danger.invalid-login')
      render 'new'
    end
    
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :logged_in_user, only: [ :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :existing_username, only: :show
  before_action :is_regular_user, only: :destroy
  
  def new
    @user = User.new
    @user.build_avatar
    
    render locals: { user: UserDecorator.new(@user) }
  end
  
  def create
    @user = User.new(user_create_params)
    
    @user.creation_ip_address = request.remote_ip
    
    if @user.save
      @user.send_activation_email
      flash[:info] = t 'user.notice.info.account-need-activation'
      redirect_to root_url
    else
      render :new, locals: { user: UserDecorator.new(@user) }
    end
  end
  
  def show

    unless @user.activated?
      redirect_to root_url and return
    end
    
    render locals: { user: UserDecorator.new(@user) }
  end
  
  def edit
    @user.build_avatar if @user.avatar.nil?
    
    render :edit, locals: { user: UserDecorator.new(@user) }
  end
  
  def update
    if @user.update_attributes(user_update_params)
      flash[:success] = t 'user.notice.success.updated'
      redirect_to users_edit_path
    else
      render :edit, locals: { user: UserDecorator.new(@user) }
    end
  end
  
  def destroy
    log_out
    @user.destroy
    flash[:success] = t 'user.notice.success.destroyed'
      
    redirect_to root_path
  end
  
  private
  
  def correct_user
    @user = @current_user
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def existing_username
    @user = User.find_by_username_lower(params[:username])
    redirect_to(root_url) unless @user
  end
  
  def is_regular_user
    redirect_to(users_dashboard_index_url) unless @user.regular?
  end
  
  def user_create_params
    params.require(:user).permit(
      :username, 
      :email,
      :password, 
      :password_confirmation,
      :time_zone,
      :description
      )
  end
  
  def user_update_params
    params.require(:user).permit(
      :username,
      :email,
      :password, 
      :password_confirmation,
      :time_zone,
      :description,
      avatar_attributes: [:kind, :uri, :uri_cache]
      )
  end
  
end

app/helpers/admin/users/filters_helper.rb
module Admin::Users::FiltersHelper
end

app/helpers/admin/users/users_helper.rb
module Admin::Users::UsersHelper
end

app/helpers/users/account_activations_helper.rb
module Users::AccountActivationsHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/password_resets_helper.rb
module Users::PasswordResetsHelper
end

app/helpers/users/preferences_helper.rb
module Users::PreferencesHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    
    user.log(:login)
  end
  
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    if (user_id = session[:user_id]) # session exists
      @current_user ||= User.find_by(id: user_id)
      
      @current_user.update_last_seen! if @current_user.present?
      
      return @current_user
    elsif (user_id = cookies.signed[:user_id]) #persistent session exists
      user = User.find_by(id: user_id)
      
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
        
        @current_user.update_last_seen! if @current_user.present?
        
        return @current_user
      end
      
    end
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !!current_user
  end
  
  def staff_member?
    logged_in? && current_user.staff_member?
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
  
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
  



end

app/views/admin/users/users/_search_form.html.erb
<%= form_tag :search_admin_users_users, method: :get do |f| %>
  <div class="input-group search-group">
  <input type="text" class="form-control" name="search" value= "<%= params[:search] %>" placeholder="<%= t 'admin.users.users.index.search_placeholder' %>">
  <span class="input-group-btn">
    <button class="btn btn-secondary" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
  </span>
</div>
<% end %>

app/views/admin/users/users/_user.html.erb
<tr>
  <td><%= user.avatar_thumbnail_tag(size: 50) %></td>
  <td><%= link_to user.username, users_show_path(user.username_lower) %></td>
  <td><%= user.email %></td>
  <td><%= t distance_of_time_in_words_to_now(user.last_seen_at) %></td>
  <td><%= t distance_of_time_in_words_to_now(user.created_at) %></td>
  <td align="right">
    <% if !current_user?(user) %>
      <%= link_to t('global.destroy-btn'), [:admin, :users, user], method: :delete, data: { confirm: t('global.destroy-confirm') } %>
    <% end %>
  </td>
</tr>

app/views/admin/users/users/index.html.erb
<% content_for :header do %>
<%= stylesheet_link_tag 'admin/users/users' %>
<% end %>

<div class="container">

  <%= render 'admin/users/shared/primary_sidebar' %>

  <div class="col-md-10">
  
    <div class="row">

    
    <div class="col-md-4 pull-md-right">
      <%= render partial: 'search_form' %>
    </div>

      <div class="col-md-12">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li class="nav-item">
            <% active = (list == "active") ? "active" : "" %>
            <%= link_to t('admin.users.users.index.tab.active'), list_admin_users_users_path(:list => 'active'), class: "nav-link #{active}" %>
          </li>
          <li class="nav-item">
            <% active = (list == "new") ? "active" : "" %>
            <%= link_to t('admin.users.users.index.tab.new'), list_admin_users_users_path(:list => 'new'), class: "nav-link #{active}" %>
          </li>
        <li class="nav-item">
          <% active = (list == "suspected") ? "active" : "" %>
          <%= link_to t('admin.users.users.index.tab.suspected'), list_admin_users_users_path(:list => 'suspected'),  class: "nav-link #{active}" %>
        </li>
        <li class="nav-item">
          <% active = (list == "blocked") ? "active" : "" %>
          <%= link_to t('admin.users.users.index.tab.blocked'), list_admin_users_users_path(:list => 'blocked'), class: "nav-link #{active}" %>
        </li>
        <li class="nav-item">
          <% active = (list == "staff") ? "active" : "" %>
          <%= link_to t('admin.users.users.index.tab.staff'), list_admin_users_users_path(:list => 'staff'), class: "nav-link #{active}" %>
        </li>
        </ul>
      </div>
    </div>

    <div class="pagination-block">
    <%= will_paginate users , :previous_label => '', :next_label => '' %>
    </div>
    
    <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th><%= t 'admin.users.users.index.username' %></th>
        <th><%= t 'admin.users.users.index.email' %></th>
        <th><%= t 'admin.users.users.index.last-seen' %></th>
        <th><%= t 'admin.users.users.index.created-at' %></th>
        <th></th>
      </tr>
    </thead>
      <tbody>
        <%= render users %>
      </tbody>
    </table>
    
    <%= will_paginate users, :previous_label => '', :next_label => '' %>
  
  </div>
</div>