config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end
  
  root 'home#index'
  
  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'
  
  namespace :admin do
    resources :dashboard, only: [:index]
      
    namespace :users do
      
      resources :users, only: [:index, :destroy] do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end
      end
      resources :filters
    end
  end
  
    namespace :users do
      
      get 'sessions/new'
      
      get 'user/edit' => 'users#edit', as: :edit
      
      get 'user/:username' => 'users#show', as: :show
      
      patch 'user' => 'users#update', as: :update
  
      delete 'user' => 'users#destroy', as: :destroy
      
      resources :users, except: [:show, :edit, :update, :destroy] do
    end

    resources :account_activations, only: [:edit]
    
    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]
    
    resources :preferences, only: [:index]
  end # namespace users

end

app/views/layouts/admin/_nav_bar.html.erb
<ul id="admin-main-nav" class="nav nav-pills">
  <li class="nav-item">
    <%= active_link_to t('admin.links.dashboard.index'), admin_dashboard_index_path, :class => 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= active_link_to t('admin.links.users.index'), admin_users_users_path, :class => 'nav-link', :active => /\/users\// %>
  </li>
</ul>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= render 'layouts/metas' %>
 
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content container">
      <%= render 'layouts/admin/nav_bar' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>