config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
  end
  
  root 'home#index'
  
  get 'home/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'signup' => 'users/users#new'
  get 'login' => 'users/sessions#new'
  post 'login' => 'users/sessions#create'
  delete 'logout' => 'users/sessions#destroy'
  
  namespace :admin do
    resources :dashboard, only: [:index]
      
    namespace :users do
      
      resources :users, only: [:index, :destroy] do
        collection do
          get 'list/:list' =>'users#index', as: :list
          get 'search', as: :search
        end
      end
      resources :filters
    end
  end
  
    namespace :users do
      
      get 'sessions/new'
      
      get 'user/edit' => 'users#edit', as: :edit
      
      get 'user/:username' => 'users#show', as: :show
      
      patch 'user' => 'users#update', as: :update
  
      delete 'user' => 'users#destroy', as: :destroy
      
      resources :users, except: [:show, :edit, :update, :destroy] do
    end

    resources :account_activations, only: [:edit]
    
    resources :password_resets, only: [:new, :create, :edit, :update]

    resources :dashboard, only: [:index]
    
    resources :preferences, only: [:index]
  end # namespace users

end

app/views/layouts/_fonts.html.erb
<!--<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>-->
<link href='https://fonts.googleapis.com/css?family=Prosto+One' rel='stylesheet' type='text/css'>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Piplet</small>
  <!--
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
  -->
</footer>

app/views/layouts/_header.html.erb
<header class="header navbar navbar-fixed-top">
  
  <div class="container">
    <div class="row">
      <div class="col-md-6">
          <!-- logo -->
          <div id="logo" class="logo">
            <a href="index.html"><%= t 'site.title' %></a>
          </div>
      </div>
      <div class="col-md-6">
        <!-- header-right start -->
        <!-- ================ -->
        <div class="content-right clearfix">
          

        <div class="main-navigation">

          <!-- navbar start -->
          <!-- ================ -->
          <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid text-xs-right">
            
            <% if logged_in? %>
            
              <ul class="nav navbar-nav  pull-md-right">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= truncate current_user.username, length: 10 %></a>
                  <div class="dropdown-menu">
                    <%= link_to t('site.menu.user.dashboard'), users_dashboard_index_path,  class: 'dropdown-item' %>
                    <%= link_to t('site.menu.user.edit'), users_edit_path, class: 'dropdown-item' %>
                    <%= link_to t('site.menu.user.preferences'), users_preferences_path, class: 'dropdown-item' %>

                    <%= link_to t('site.menu.user.notifications'), '#', class: 'dropdown-item' %>
                    
                    <div class="dropdown-divider"></div>
                    <%= link_to t('site.menu.user.log-out'), logout_path(current_user), method: 'delete', class: 'dropdown-item' %>
                  </div>
                  </li>
                  
                  <li class="nav-item dropdown nav-general">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                    <div class="dropdown-menu">
                      <% if staff_member? %>
                        <%= link_to t('site.menu.general.admin'), admin_dashboard_index_path,  class: 'dropdown-item' %>
                          <div class="dropdown-divider"></div>
                        <% end %>
                      <%= link_to t('site.menu.general.about'), '#', class: 'dropdown-item' %>
                      <%= link_to t('site.menu.general.help'), '#', class: 'dropdown-item' %>
                    </div>
                    </li>
              </ul>
              
            <% else %>
              <%= link_to t('user.links.log-in'), login_path, class: 'link-primary', role: 'button' %>
              <%= link_to t('user.links.sign-up'), signup_path, class: 'link-primary', role: 'button' %>
            <% end %>



            </div>
          </nav>
          <!-- navbar end -->

        </div>
        <!-- main-navigation end -->  
        </div>
        <!-- header-right end -->
  
      </div>
    </div>
  </div>
  
</header>
<!-- header end -->

app/views/layouts/_metas.html.erb
<%= render 'layouts/fonts' %>
<%= stylesheet_link_tag 'application', media: 'all' %>

<%= stylesheet_link_tag 'admin', media: 'all' if staff_member? %>

<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>

<%= yield(:header) if content_for? :header %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= render 'layouts/metas' %>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>